name: Applying

# Triggers for the workflow
on:
  push:
    branches:
      - main
  workflow_dispatch:

# Define jobs in the workflow
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Check out the code from the repository
      - name: Checkout code
        uses: actions/checkout@v4
      
      # Configure AWS credentials using GitHub Secrets for secure access
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: AKIAXYKJRKBBNMFDED5U
          aws-secret-access-key: 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
          aws-region: us-east-1

      # Update kubeconfig to authenticate to the EKS cluster
      - name: Update kubeconfig for EKS
        run: aws eks --region us-east-1 update-kubeconfig --name Cluster1

      # Apply Persistent Volume and PVC configurations
      - name: Apply PVC and PV
        run: |
          kubectl apply -f db/pv.yaml
          kubectl apply -f db/pvc.yaml
 
      # Deploy PostgreSQL (If you have any additional configurations)
      - name: Deploy PostgreSQL
        run: kubectl apply -f db/postgresql-deployment.yaml
        
      - name: Explose PostgreSQL deployment
        run : kubectl apply -f db/postgresql-service.yaml

      - name : Get PV
        run: kubectl get pv

      - name : Get PVC
        run : kubectl get pvc

      - name : Get Deployments
        run : kubectl get deployments

      - name : Get Pods
        run : kubectl get pods

      - name : Describe the deployment
        run : kubectl describe deployment postgresql

      - name : Describe Pod
        run : kubectl describe pod postgresql-77d75d45d5-lf6tx
        
      - name : Get svc
        run : kubectl get svc
        
      - name : Set up port-forwarding to `postgresql-service`
        run : kubectl port-forward svc/postgresql-service 5433:5432 &

      # Retrieve the PostgreSQL password
      - name: Retrieve PostgreSQL Password
        id: get-postgres-password
        run: |
          export POSTGRES_PASSWORD=$(kubectl get secret --namespace default coworking-db-postgresql -o jsonpath="{.data.postgres-password}" | base64 -d)
          echo "POSTGRES_PASSWORD=$POSTGRES_PASSWORD" >> $GITHUB_ENV

      # Apply Seed Files
      - name: Apply Seed Files
        env:
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
        run: |
          POD_NAME=$(kubectl get pods -n default -l app.kubernetes.io/name=postgresql -o jsonpath="{.items[0].metadata.name}")

          # Execute seed files
          for file in _create_tables.sql _seed_use.sql _seed_token.sql; do
            echo "Applying $file..."
            kubectl exec $POD_NAME -n default -- bash -c "PGPASSWORD=\"$POSTGRES_PASSWORD\" psql postgres://postgres@localhost:5432/postgres -f /db/$file"
          done

          # Verify seed data
          kubectl exec $POD_NAME -n default -- bash -c "PGPASSWORD=\"$POSTGRES_PASSWORD\" psql postgres://postgres@localhost:5432/postgres -c 'SELECT COUNT(*) FROM your_table;'"



