name: Create EKS Cluster
on: [workflow_dispatch]

jobs:
  create-cluster:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: AKIA44Y6CHB342IQVBHP
          aws-secret-access-key: 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
          aws-region: us-west-1

      - name: Install eksctl
        run: |
          curl --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" \
          | tar xz -C /tmp
          sudo mv /tmp/eksctl /usr/local/bin

      - name: Create EKS Cluster
        run: eksctl create cluster --name my-cluster --nodes=2 --version=1.30 --instance-types=t2.medium --region=us-west-1

      - name: Update Kubeconfig
        run: aws eks --region us-west-1 update-kubeconfig --name my-cluster

      - name: Verify Current Context
        run: kubectl config current-context
