# Workflow name for the frontend continuous deployment pipeline
name: Continuous Deployment

# Triggers for the workflow
on:
  # Trigger the workflow on any push to the main branch
  push:
    branches:
      - main
  # Allow manual execution of the workflow through the GitHub Actions UI
  workflow_dispatch:

# Define jobs in the workflow
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Check out the code from the repository
      - name: Checkout code
        uses: actions/checkout@v4
      
      # Configure AWS credentials using GitHub Secrets for secure access
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: AKIAXYKJRKBBNMFDED5U
          aws-secret-access-key: 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
          aws-region: us-east-2

      # Update kubeconfig to authenticate to the EKS cluster
      - name: Update kubeconfig for EKS
        run: aws eks --region us-east-1 update-kubeconfig --name my-cluster



      - name: Apply YAML configurations
        run: |
          kubectl apply -f pvc.yaml
          kubectl apply -f pv.yaml
          kubectl apply -f postgresql-deployment.yaml
        
      # Get and display service URLs to verify deployment
      - name: Get Service URLs
        run: kubectl get svc -A

      # Get and display service Nodes
      - name: Get Service Pods
        run: kubectl get nodes
